/**
 * BuiltIn3
 *
 * This class is used to test Built In Predicate functionality.
 * The BuiltIn3 predicate has 3 arguments:
 *
 *    builtin3(InList, OutHead, OutTail)
 *
 * @author   Klivo
 * @version 1.0
 */

import java.util.*;
import inferencilo.*;

public class BuiltIn3 extends BuiltInPredicateIHT {

   /**
    * constructor
    *
    * @param  unifiable parameters
    */
   public BuiltIn3(Unifiable... args) {
      super("BuiltIn3", args);
   }


   /*
    * clearAll - indicate failure
    */
   private void clearAll() {
      newHead = null;
      newTail = null;
   }


   /**
    * evaluate
    *
    * The unique work of the built-in predicate is done by this method.
    * Results are saved in newHead, newTail, and newErrorList.
    *
    * @param   substitution set of parent
    * @return  unifiable term or null
    */
   public Unifiable evaluate(SubstitutionSet ss) {

      clearAll();

      PList inList = castPList(arguments[0], ss);
      if (inList == null) return null;

      Constant head = castConstant(inList.getHead(), ss);
      newHead = new Constant("" + head);
      newTail = inList.getTail();
      return newHead;
   }

   /**
    * getHead
    *
    * Get head term generated by evaluate().
    *
    * @return head term
    */
   Unifiable newHead = null;
   public Unifiable getHead() { return newHead; }

   /**
    * getTail
    *
    * Get tail term generated by evaluate().
    *
    * @return tail term
    */
   Unifiable newTail = null;
   public Unifiable getTail() { return newTail; }

} // BuiltIn3
