/**
 * BuiltIn4
 *
 * This class is used to test Built In Predicate functionality.
 * BuiltIn4 has 4 arguments:
 *
 *    word list in
 *    word list out
 *    error list in
 *    error list out
 *
 * @author   Klivo
 * @version 1.0
 */

import java.util.*;
import inferencilo.*;

public class BuiltIn4 extends BuiltInPredicateIOIO {

   /**
    * constructor
    *
    * @param  unifiable arguments
    */
   public BuiltIn4(Unifiable... args) {
      super("BuiltIn4", args);
   }


   /**
    * evaluate
    *
    * The unique work of the built-in predicate is done by this method.
    *
    * @return  unifiable term or null
    * @param   substitution set of parent
    */
   public Unifiable evaluate(SubstitutionSet ss) {
      Constant err = new Constant("second error");
      newErrorList = new PList(false, err, arguments[2]);
      return PList.make("[transformed list]");
   }

   /**
    * getErrors
    *
    * Return errors generated by evaluate().
    *
    * @return  new list of errors
    */
   Unifiable newErrorList = null;
   public Unifiable getErrors() { return newErrorList; }

} // BuiltIn4
